### ISSUE TITLE
Dependency issue with mailjet/mailjet-swiftmailer

### ISSUE THREAD

**Issue by janhenckens** [bertoost/Craft-3-Mailjet#1]
Hey Bert

I'm running into an error when installing this plugin on a news Craft site:

`  Problem 1
    - Installation request for mailjet/mailjet-apiv3-php (locked at dev-master) -> satisfiable by mailjet/mailjet-apiv3-php[dev-master].
    - bertoost/craft-mailjet 1.1.0 requires mailjet/mailjet-swiftmailer dev-upgradeToSwiftmailer6 -> satisfiable by mailjet/mailjet-swiftmailer[dev-upgradeToSwiftmailer6].
    - bertoost/craft-mailjet 1.1.1 requires mailjet/mailjet-swiftmailer dev-upgradeToSwiftmailer6 -> satisfiable by mailjet/mailjet-swiftmailer[dev-upgradeToSwiftmailer6].
    - bertoost/craft-mailjet 1.1.2 requires mailjet/mailjet-swiftmailer dev-upgradeToSwiftmailer6 -> satisfiable by mailjet/mailjet-swiftmailer[dev-upgradeToSwiftmailer6].
    - Conclusion: don't install mailjet/mailjet-swiftmailer dev-upgradeToSwiftmailer6
    - Installation request for bertoost/craft-mailjet ^1.1 -> satisfiable by bertoost/craft-mailjet[1.1.0, 1.1.1, 1.1.2].`

It seems to go wrong with `mailjet/mailjet-swiftmailer dev-upgradeToSwiftmailer6`
I tried playing around with the versions but not sure what breaks the plugin and what won't...

Can you have a look?

Thanks!

**Comment by bertoost** [comment]
Hi @janhenckens 
Did you see the temporary notice in the readme?
https://github.com/bertoost/Craft-3-Mailjet#temporary-note 😉 
As I saw they have merged the branch, but have to check that soon.

**Comment by janhenckens** [comment]
Yes, I had that in my composer.json before I tried installing, results in in this error.

**Comment by janhenckens** [comment]
This turned out to be an issues cause by an other plugin we're using on this project (https://github.com/cultuurnet/mailjet-subscribe). Updated that and now this installs too.
