### ISSUE TITLE
PHP requirement causing installation error

### ISSUE THREAD

**Issue by chadcrowell** [bertoost/Craft-3-Mailjet#3]
```Problem 1
- Installation request for bertoost/craft-mailjet 1.2.0 -> satisfiable by bertoost/craft-mailjet[1.2.0].
- bertoost/craft-mailjet 1.2.0 requires php ^7.2 -> your PHP version (7.3.15-3+ubuntu18.04.1+deb.sury.org+1) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.```

Can you specify a different PHP version requirement format, or is there something else that can be done to get past this issue? I'm using Vagrant/Virtualbox locally.

**Comment by chadcrowell** [comment]
Just found and fixed. For anyone else... in the main Craft composer.json file for your project, you are going to see this:

```
"config": {
    "sort-packages": true,
    "optimize-autoloader": true,
    "platform": {
      "php": "7.0"
    }
  },
```

This plugin requires php 7.2 or higher, so changing 7.0 to 7.2 (as long as you are running php 7.2 or higher in your environment) allows this plugin to install.

**Comment by bertoost** [comment]
@chadcrowell sorry for not being that quickly ;-) 
but as it may sounds logic.. change it to the php version you run your application in. So, as per output of your initial comment, you run v7.3.15, change it to 7.3. Keep things in line with your environment.
