### ISSUE TITLE
Missing void in SmsService leads to PHP Compile Error

### ISSUE THREAD

**Issue by menberg** [bertoost/Craft-3-Mailjet#4]
The declaration of  public function init() lacks a ": void" which leads to a PHP Compile Error with error message "Declaration of bertoost\\mailjet\\services\\SmsService::init() must be compatible with bertoost\\mailjet\\services\\AbstractService::init(): void"

A possible fix would be to add ": void" to the following line:
https://github.com/bertoost/Craft-3-Mailjet/blob/711061078561f3cc8ed2656fa4aa1aeea93b938e/src/services/SmsService.php#L28

Thanks for your wonderful work on this plugin.

**Comment by bertoost** [comment]
Good catch! It was added in the last update, without checking sub classes.
Will fix is later today. Thanks! 👍

**Comment by menberg** [comment]
Thank you. Wonderful. Might there be also a chance to review https://github.com/bertoost/Craft-3-Mailjet/pull/2 by the way? Thanks and have a nice day!

**Comment by bertoost** [comment]
Yes. Thanks.

**Comment by bertoost** [comment]
Released soon!
