### ISSUE TITLE
PHP 7.4 Compatibility

### ISSUE THREAD

**Issue by jaredchesebro** [bertoost/Craft-3-Mailjet#5]
When I tried to install using composer in command line got the following message: 

`[InvalidArgumentException]                                                                                                    
  Package bertoost/craft-mailjet has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version`

I'm using PHP 7.4 and don't plan on downgrading to use your plugin. I'll stick with using SMTP for now.

**Comment by bertoost** [comment]
Thats probably because you have a restriction in your composer.sjon. As far I can remember, it's in the "extra" config area where you have defined your php version, lower than used. I use PHP7.4 myself with this plugin as well

**Comment by jaredchesebro** [comment]
That's really odd. I would've thought Craft would handle updating that setting. Thanks for pointing that out.

**Comment by jaredchesebro** [comment]
That worked. Feel free to close the issue!

**Comment by bertoost** [comment]
Great @jaredchesebro :-)
